events {}
http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    server {
        listen 80;
        root /usr/share/nginx/html;
        index index.html;
        location /supabase/ {
            proxy_pass https://wsbnlafqcvqizlhaeffb.supabase.co/;
            proxy_ssl_server_name on;
            proxy_set_header Host wsbnlafqcvqizlhaeffb.supabase.co;
            proxy_set_header apikey "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndzYm5sYWZxY3ZxaXpsaGFlZmZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUwMTc5MjgsImV4cCI6MjA5MDU5MzkyOH0.aGuDJcRDPCr1GsqEv6QmUsfa-8bcSCl0tBhg4XBd4Wk";
            proxy_set_header Authorization "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndzYm5sYWZxY3ZxaXpsaGFlZmZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUwMTc5MjgsImV4cCI6MjA5MDU5MzkyOH0.aGuDJcRDPCr1GsqEv6QmUsfa-8bcSCl0tBhg4XBd4Wk";
        }
        location = / {
            try_files /index.html =404;
        }
        location / {
            try_files $uri =404;
        }
    }
}